apiVersion: apps/v1
kind: Deployment
metadata:
  name:tomcat-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat-deployment
    spec:
      containers:
      - name: tomcat-webserver
        image: tomcat
        ports:
        - containerPort: 80
