apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app-name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: nginx
  template:
    metadata:
      labels:
        app-name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
