apiVersion: v1
kind: Pod
metadata:
  name: nginx-debian
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: container1-nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: container2-debian
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
